# src/decisions/consumption_quantity.py
"""
Decision 6: consumption_quantity

Determines the total quantity of items an agent wishes to purchase during the term
and generates purchase requests with timestamps.

Default behavior (when not simulated):
1. Uses agent's income (generated by disclose_documents) to assign income category
2. Gets consumption limit for that category from Page 1 configuration
3. Generates random total quantity in [0, limit]
4. Creates purchase requests (1 item each) with random timestamps across term

When fully simulated (future):
- More sophisticated models for quantity per purchase
- Consideration of agent traits, budget constraints, etc.
"""
import numpy as np
from typing import Dict, Any, Optional

from src.decisions.income_utils import get_agent_income, get_simulation_param


def _assign_income_category(income: float, simulation_config: Optional[Dict]) -> int:
    """
    Assign agent to an income category (1 to N) based on their income.
    
    PROFESSOR'S SPECIFICATION:
    - The income range is split into N equal intervals
    - ALL customers (discount, fixed, regular) are assigned to categories based ONLY on income
    - NO distinction by customer type during category assignment
    - Customer type only affects which consumption limit applies (not which category)
    
    Example with N=10 and income range [$0, $100,000]:
        Category 1:  [$0,      $10,000)   - Lowest income
        Category 2:  [$10,000, $20,000)
        Category 3:  [$20,000, $30,000)
        ...
        Category 10: [$90,000, $100,000]  - Highest income
    
    Args:
        income: Agent's annual income (dollar amount)
        simulation_config: Contains num_fixed_categories and distribution parameters
        
    Returns:
        Income category number (1 to N, where N = num_fixed_categories)
    """
    # Get number of income categories from Page 1
    num_categories = get_simulation_param(simulation_config, 'num_fixed_categories', 10)
    num_categories = max(1, int(num_categories))
    
    # If only 1 category exists, everyone goes there
    if num_categories == 1:
        return 1
    
    # STEP 1: Determine the full income range (min to max)
    # This depends on the distribution type configured on Page 1
    dist_type = get_simulation_param(simulation_config, 'income_distribution', 'lognormal')
    
    # Get minimum income
    if dist_type == 'lognormal':
        min_income = get_simulation_param(simulation_config, 'lognormal_min', 0.0)
    elif dist_type == 'generalised_gamma':
        min_income = get_simulation_param(simulation_config, 'gg_min', 0.0)
    elif dist_type == 'dagum':
        min_income = get_simulation_param(simulation_config, 'dagum_min', 0.0)
    else:
        min_income = get_simulation_param(simulation_config, 'income_min', 0.0)
    
    # Get maximum income
    if dist_type == 'lognormal':
        max_income = get_simulation_param(simulation_config, 'lognormal_max', None)
        # If no max specified, estimate using mean + 3*std
        if max_income is None:
            mu = get_simulation_param(simulation_config, 'lognormal_mu', 10.0)
            sigma = get_simulation_param(simulation_config, 'lognormal_sigma', 0.5)
            mean = min_income + np.exp(mu + 0.5 * sigma**2)
            std = np.sqrt((np.exp(sigma**2) - 1) * np.exp(2*mu + sigma**2))
            max_income = mean + 3 * std
    elif dist_type == 'generalised_gamma':
        max_income = get_simulation_param(simulation_config, 'gg_max', None)
        if max_income is None:
            max_income = get_simulation_param(simulation_config, 'gg_lambda', 20000.0) * 3
    elif dist_type == 'dagum':
        max_income = get_simulation_param(simulation_config, 'dagum_max', None)
        if max_income is None:
            max_income = get_simulation_param(simulation_config, 'dagum_b', 25000.0) * 3
    else:
        max_income = get_simulation_param(simulation_config, 'income_max', 100000.0)
    
    # Safety check: ensure max > min
    if max_income <= min_income:
        max_income = min_income + 100000.0  # Default range
    
    # STEP 2: Calculate interval width
    income_range = max_income - min_income
    interval_width = income_range / num_categories
    
    # STEP 3: Determine which interval the agent's income falls into
    # Category i contains incomes in range [min + (i-1)*width, min + i*width)
    # Special case: Category N includes the upper bound
    
    if income <= min_income:
        # Edge case: income at or below minimum → Category 1
        return 1
    elif income >= max_income:
        # Edge case: income at or above maximum → Category N (highest)
        return num_categories
    else:
        # Normal case: find which interval contains this income
        position = (income - min_income) / income_range  # Fraction in [0, 1]
        category_index = int(np.floor(position * num_categories))  # 0 to N-1
        category = category_index + 1  # Convert to 1-based (1 to N)
        
        # Safety clamp to valid range
        category = max(1, min(category, num_categories))
        
        return int(category)


def consumption_quantity(agent_state: dict, params: dict, rng: np.random.Generator, 
                        simulation_config: dict = None, **kwargs) -> dict:
    """
    Decision 6: Determine consumption quantity and generate purchase requests.
    
    Default behavior (this implementation):
    1. Get/generate agent income
    2. Assign to income category (1 to NFIC)
    3. Look up consumption limit for that category
    4. Generate random total quantity in [0, limit]
    5. Create purchase requests (1 item each) spread randomly across term
    
    Args:
        agent_state: Agent's state dict (includes 'income' if set by disclose_documents)
        params: Decision-specific parameters from decisions.yaml
        rng: Random number generator for reproducibility
        simulation_config: Page 1 parameters in ['simulation'] sub-dict
        
    Returns:
        Dictionary with:
        - consumption_quantity: Total items to purchase (int)
        - purchase_requests: List of dicts with request_id, quantity=1, timestamp_hours
        - income_category: Assigned category (int, 1 to NFIC)
        - income: Agent income (stored for consistency)
    """
    
    # STEP 1: Get or generate agent income using centralized utility
    # Income should already exist from disclose_documents (Decision 2)
    # If not, get_agent_income will generate it using Page 1 parameters
    income = get_agent_income(agent_state, simulation_config, rng)
    
    # STEP 2: Assign agent to income category (1 to NFIC)
    income_category = _assign_income_category(income, simulation_config)
    
    # STEP 3: Get consumption limit for this category
    # Check if consumption limits are enabled and configured
    consumption_limits = {}
    if isinstance(simulation_config, dict):
        consumption_limits = simulation_config.get('consumption_limits', {}) or {}
    
    # Get fallback maximum for when limits are disabled
    fallback_max = get_simulation_param(simulation_config, 'max_purchases_per_term', 50)
    fallback_max = max(0, int(fallback_max))
    
    # Look up limit for this category
    limit_key = f"cat_{income_category}"
    if isinstance(consumption_limits, dict) and limit_key in consumption_limits:
        try:
            consumption_limit = int(consumption_limits[limit_key])
        except (ValueError, TypeError):
            consumption_limit = fallback_max
    else:
        # No limit configured for this category - use fallback
        consumption_limit = fallback_max
    
    consumption_limit = max(0, consumption_limit)  # Ensure non-negative
    
    # STEP 4: Generate total quantity for the term
    # Random integer in [0, consumption_limit] inclusive
    if consumption_limit > 0:
        total_quantity = int(rng.integers(0, consumption_limit + 1))
    else:
        total_quantity = 0
    
    # STEP 5: Generate purchase requests with timestamps and transaction fields
    # Professor's specification: each request = 1 item for defaults
    # Timestamps spread randomly across term duration
    # 
    # NEW: Include transaction fields that are known at this stage:
    # - customer_id (agent ID)
    # - customer_type (from disclose_documents)
    # - vendorID (default 1 for now)
    # - platformPrice and bid_value will be filled by enrich_purchase_requests (Decision 6b)
    
    purchase_requests = []
    
    if total_quantity > 0:
        # Calculate term duration from Page 1 parameters
        periods = get_simulation_param(simulation_config, 'periods', 1)
        duration_hours = get_simulation_param(simulation_config, 'duration_hours', 1.0)
        term_duration = float(periods * duration_hours)
        
        # Generate random timestamps uniformly distributed in [0, term_duration]
        # Sort them so they're in chronological order
        timestamps = sorted(rng.uniform(0, term_duration, size=total_quantity))
        
        # Get agent ID (use agent_id if available, otherwise index + 1)
        agent_id = agent_state.get('agent_id', agent_state.get('index', 0) + 1)
        
        # Get customer type from agent_state (should be set by disclose_documents)
        from src.decisions.income_utils import get_customer_type
        customer_type = get_customer_type(agent_state, simulation_config)
        
        # Create purchase request objects with transaction fields
        for i, timestamp in enumerate(timestamps):
            purchase_requests.append({
                "request_id": i + 1,
                "quantity": 1,  # 1 item per request for defaults
                "timestamp_hours": float(timestamp),
                
                # Transaction fields (matching Excel export format)
                "customer_id": int(agent_id),
                "customer_type": customer_type,  # "discount", "fixed", or "regular"
                "vendorID": 1,  # Default vendor ID (can be updated by vendor_selection later)
                
                # These will be filled by enrich_purchase_requests (Decision 6b)
                "platformPrice": None,  # Will be "DISCOUNT", "FIXED", "PN", or "BID"
                "bid_value": None       # Will be actual bid amount or "N/A"
            })
    
    # Return results
    return {
        "consumption_quantity": int(total_quantity),
        "purchase_requests": purchase_requests,
        "income_category": int(income_category),
        "income": float(income)  # Store/update income for consistency
    }


