# src/decisions/consumption_quantity.py
"""
Decision 6: consumption_quantity

Determines the total quantity of items an agent wishes to purchase during the term
and generates purchase requests with timestamps.

Default behavior (when not simulated):
1. Uses agent's income to assign to an income category (equal interval division)
2. Determines customer type (discount, fixed, or regular)
3. Gets consumption limit based on customer type:
   - Discount customers: Use Category 1 limit (lowest)
   - Regular customers: Use Category N limit (highest)
   - Fixed customers: Use their actual income category limit
4. Generates random total quantity in [0, limit]
5. Creates purchase requests (1 item each) with random timestamps across term

When fully simulated (future):
- More sophisticated models for quantity per purchase
- Consideration of agent traits, budget constraints, etc.
"""
import numpy as np
from typing import Dict, Any, Optional

from src.decisions.income_utils import get_agent_income, get_simulation_param


def _assign_income_category(income: float, simulation_config: Optional[Dict]) -> int:
    """
    Assign agent to an income category (1 to N) based on their income.
    
    PROFESSOR'S SPECIFICATION:
    - The income range is split into N equal intervals
    - ALL customers (discount, fixed, regular) are assigned to categories based ONLY on income
    - NO distinction by customer type during category assignment
    - Customer type only affects which consumption limit applies (not which category)
    
    IMPLEMENTATION:
    - Uses the ACTUAL income range generated by the income generation system
    - Min = PPF(0.00) - the lowest percentile used (Level 1 agents)
    - Max = PPF(1.00) or configured max - the highest percentile used (Level 5 agents)
    - This ensures categories match the real income distribution, not theoretical bounds
    
    Example with Lognormal(μ=10, σ=0.5) and N=14:
        Min income: ~$4,697 (PPF(0.00))
        Max income: ~$176,000 (PPF(1.00))
        Category 1:  [$4,697  - $16,943)   - Populated by Level 1 agents
        Category 2:  [$16,943 - $29,189)
        ...
        Category 14: [$151,508 - $176,000]  - Populated by Level 5 agents
    
    Args:
        income: Agent's annual income (dollar amount)
        simulation_config: Contains num_fixed_categories and distribution parameters
        
    Returns:
        Income category number (1 to N, where N = num_fixed_categories)
    """
    # Get number of income categories from Page 1
    num_categories = get_simulation_param(simulation_config, 'num_fixed_categories', 10)
    num_categories = max(1, int(num_categories))
    
    # If only 1 category exists, everyone goes there
    if num_categories == 1:
        return 1
    
    # STEP 1: Determine the ACTUAL income range that can be generated
    # This matches what _generate_income_within_percentile_range() produces
    # Level 1 uses percentile 0.00-0.20, Level 5 uses 0.80-1.00
    # So the actual range is PPF(0.00) to PPF(1.00)
    
    dist_type = get_simulation_param(simulation_config, 'income_distribution', 'lognormal')
    sim_params = simulation_config.get('simulation', {}) if simulation_config else {}
    
    # Calculate min_income using PPF(0.00) - the actual minimum that can be generated
    if dist_type == 'dagum':
        # Dagum: use inverse CDF formula for percentile 0.00
        a = get_simulation_param(simulation_config, 'dagum_a', 2.0)
        p = get_simulation_param(simulation_config, 'dagum_p', 1.5)
        b = get_simulation_param(simulation_config, 'dagum_b', 25000.0)
        min_val = get_simulation_param(simulation_config, 'dagum_min', 0.0)
        
        # PPF(0.00) for Dagum approaches min_val
        # Use a very small percentile instead (PPF of near-zero)
        small_percentile = 0.0001
        Y_min = b * np.power(np.power(small_percentile, -1/p) - 1, -1/a)
        min_income = min_val + Y_min
    else:
        # For lognormal, generalised_gamma, etc: use scipy
        from scipy import stats
        
        if dist_type == 'lognormal':
            mu = get_simulation_param(simulation_config, 'lognormal_mu', 10.0)
            sigma = get_simulation_param(simulation_config, 'lognormal_sigma', 0.5)
            loc = get_simulation_param(simulation_config, 'lognormal_min', 0.0)
            dist = stats.lognorm(s=sigma, scale=np.exp(mu), loc=loc)
        elif dist_type == 'generalised_gamma':
            k = get_simulation_param(simulation_config, 'gg_k', 1.5)
            c = get_simulation_param(simulation_config, 'gg_c', 2.0)
            lambda_param = get_simulation_param(simulation_config, 'gg_lambda', 20000.0)
            loc = get_simulation_param(simulation_config, 'gg_min', 0.0)
            dist = stats.gengamma(a=c, c=k, scale=lambda_param, loc=loc)
        else:
            # Fallback: uniform distribution
            min_val = get_simulation_param(simulation_config, 'income_min', 0.0)
            max_val = get_simulation_param(simulation_config, 'income_max', 100000.0)
            dist = stats.uniform(loc=min_val, scale=max_val - min_val)
        
        # Use a very small percentile (not exactly 0.00 to avoid numerical issues)
        min_income = dist.ppf(0.0001)
    
    # Calculate max_income using PPF(1.00) or configured max
    if dist_type == 'dagum':
        max_income = get_simulation_param(simulation_config, 'dagum_max', None)
        if max_income is None:
            # Use a high percentile for Dagum (approaching 1.00)
            high_percentile = 0.9999
            Y_max = b * np.power(np.power(high_percentile, -1/p) - 1, -1/a)
            max_income = min_val + Y_max
    else:
        # Check if there's a configured max
        if dist_type == 'lognormal':
            max_income = get_simulation_param(simulation_config, 'lognormal_max', None)
        elif dist_type == 'generalised_gamma':
            max_income = get_simulation_param(simulation_config, 'gg_max', None)
        else:
            max_income = get_simulation_param(simulation_config, 'income_max', None)
        
        # If no max configured, use PPF(0.9999) to get the actual high end
        if max_income is None:
            max_income = dist.ppf(0.9999)
    
    # Safety check: ensure max > min
    if max_income <= min_income:
        max_income = min_income + 100000.0  # Default range
    
    # STEP 2: Calculate interval width
    income_range = max_income - min_income
    interval_width = income_range / num_categories
    
    # STEP 3: Determine which interval the agent's income falls into
    # Category i contains incomes in range [min + (i-1)*width, min + i*width)
    # Special case: Category N includes the upper bound
    
    if income <= min_income:
        # Edge case: income at or below minimum → Category 1
        return 1
    elif income >= max_income:
        # Edge case: income at or above maximum → Category N (highest)
        return num_categories
    else:
        # Normal case: find which interval contains this income
        position = (income - min_income) / income_range  # Fraction in [0, 1]
        category_index = int(np.floor(position * num_categories))  # 0 to N-1
        category = category_index + 1  # Convert to 1-based (1 to N)
        
        # Safety clamp to valid range
        category = max(1, min(category, num_categories))
        
        return int(category)


def consumption_quantity(agent_state: dict, params: dict, rng: np.random.Generator, 
                        simulation_config: dict = None, **kwargs) -> dict:
    """
    Decision 6: Determine consumption quantity and generate purchase requests.
    
    Default behavior (this implementation):
    1. Get/generate agent income
    2. Assign to income category (1 to NFIC) based on equal intervals
    3. Determine customer type (discount/fixed/regular)
    4. Get consumption limit based on customer type:
       - Discount: Use Category 1 limit
       - Regular: Use Category N limit  
       - Fixed: Use actual income category limit
    5. Generate random total quantity in [0, limit]
    6. Create purchase requests (1 item each) spread randomly across term
    
    Args:
        agent_state: Agent's state dict (includes 'income' if set by disclose_documents)
        params: Decision-specific parameters from decisions.yaml
        rng: Random number generator for reproducibility
        simulation_config: Page 1 parameters in ['simulation'] sub-dict
        
    Returns:
        Dictionary with:
        - consumption_quantity: Total items to purchase (int)
        - purchase_requests: List of dicts with request_id, quantity=1, timestamp_hours
        - income_category: Assigned category (int, 1 to NFIC)
        - income: Agent income (stored for consistency)
    """
    
    # STEP 1: Get or generate agent income using centralized utility
    # Income should already exist from disclose_documents (Decision 2)
    # If not, get_agent_income will generate it using Page 1 parameters
    income = get_agent_income(agent_state, simulation_config, rng)
    
    # STEP 2: Assign agent to income category (1 to NFIC)
    income_category = _assign_income_category(income, simulation_config)
    
    # STEP 3: Determine customer type (discount, fixed, or regular)
    from src.decisions.income_utils import get_customer_type
    customer_type = get_customer_type(agent_state, simulation_config)
    
    # STEP 4: Get consumption limit based on CUSTOMER TYPE
    # According to professor's specification:
    # - Discount customers: Use Category 1 limit (lowest)
    # - Regular customers: Use Category N limit (highest)
    # - Fixed customers: Use their actual income category limit
    
    # Check if consumption limits are enabled and configured
    consumption_limits = {}
    if isinstance(simulation_config, dict):
        consumption_limits = simulation_config.get('consumption_limits', {}) or {}
    
    # Get fallback maximum for when limits are disabled
    fallback_max = get_simulation_param(simulation_config, 'max_purchases_per_term', 50)
    fallback_max = max(0, int(fallback_max))
    
    # Determine which category's limit to use based on customer type
    num_categories = get_simulation_param(simulation_config, 'num_fixed_categories', 10)
    
    if customer_type == "discount":
        # Discount customers always use Category 1 limit (lowest)
        limit_category = 1
    elif customer_type == "regular":
        # Regular customers always use Category N limit (highest)
        limit_category = num_categories
    else:  # customer_type == "fixed"
        # Fixed customers use their actual income category limit
        limit_category = income_category
    
    # Look up limit for the determined category
    limit_key = f"cat_{limit_category}"
    if isinstance(consumption_limits, dict) and limit_key in consumption_limits:
        try:
            consumption_limit = int(consumption_limits[limit_key])
        except (ValueError, TypeError):
            consumption_limit = fallback_max
    else:
        # No limit configured for this category - use fallback
        consumption_limit = fallback_max
    
    consumption_limit = max(0, consumption_limit)  # Ensure non-negative
    
    # STEP 5: Generate total quantity for the term
    # Random integer in [0, consumption_limit] inclusive
    if consumption_limit > 0:
        total_quantity = int(rng.integers(0, consumption_limit + 1))
    else:
        total_quantity = 0
    
    # STEP 6: Generate purchase requests with timestamps and transaction fields
    # Professor's specification: each request = 1 item for defaults
    # Timestamps spread randomly across term duration
    # 
    # NEW: Include transaction fields that are known at this stage:
    # - customer_id (agent ID)
    # - customer_type (from disclose_documents)
    # - vendorID (default 1 for now)
    # - platformPrice and bid_value will be filled by enrich_purchase_requests (Decision 6b)
    
    purchase_requests = []
    
    if total_quantity > 0:
        # Calculate term duration from Page 1 parameters
        periods = get_simulation_param(simulation_config, 'periods', 1)
        duration_hours = get_simulation_param(simulation_config, 'duration_hours', 1.0)
        term_duration = float(periods * duration_hours)
        
        # Generate random timestamps uniformly distributed in [0, term_duration]
        # Sort them so they're in chronological order
        timestamps = sorted(rng.uniform(0, term_duration, size=total_quantity))
        
        # Get agent ID (use agent_id if available, otherwise index + 1)
        agent_id = agent_state.get('agent_id', agent_state.get('index', 0) + 1)
        
        # Get customer type from agent_state (should be set by disclose_documents)
        from src.decisions.income_utils import get_customer_type
        customer_type = get_customer_type(agent_state, simulation_config)
        
        # Create purchase request objects with transaction fields
        for i, timestamp in enumerate(timestamps):
            purchase_requests.append({
                "request_id": i + 1,
                "quantity": 1,  # 1 item per request for defaults
                "timestamp_hours": float(timestamp),
                
                # Transaction fields (matching Excel export format)
                "customer_id": int(agent_id),
                "customer_type": customer_type,  # "discount", "fixed", or "regular"
                "vendorID": 1,  # Default vendor ID (can be updated by vendor_selection later)
                
                # These will be filled by enrich_purchase_requests (Decision 6b)
                "platformPrice": None,  # Will be "DISCOUNT", "FIXED", "PN", or "BID"
                "bid_value": None       # Will be actual bid amount or "N/A"
            })
    
    # Return results
    return {
        "consumption_quantity": int(total_quantity),
        "purchase_requests": purchase_requests,
        "income_category": int(income_category),
        "income": float(income)  # Store/update income for consistency
    }


