# src/decisions/consumption_quantity.py
"""
Decision 6: consumption_quantity

Determines the total quantity of items an agent wishes to purchase during the term
and generates purchase requests with timestamps.

Default behavior (when not simulated):
1. Uses agent's income (generated by disclose_documents) to assign income category
2. Gets consumption limit for that category from Page 1 configuration
3. Generates random total quantity in [0, limit]
4. Creates purchase requests (1 item each) with random timestamps across term

When fully simulated (future):
- More sophisticated models for quantity per purchase
- Consideration of agent traits, budget constraints, etc.
"""
import numpy as np
from typing import Dict, Any, Optional


def _get_simulation_param(simulation_config: Optional[Dict], key: str, default=None):
    """
    Helper to safely extract parameters from simulation_config.
    
    Args:
        simulation_config: Config dict with 'simulation' sub-dict containing Page 1 parameters
        key: Parameter name to retrieve
        default: Fallback value if not found
        
    Returns:
        Parameter value from simulation_config['simulation'][key] or default
    """
    if not simulation_config or not isinstance(simulation_config, dict):
        return default
    
    sim = simulation_config.get('simulation', {})
    return sim.get(key, default)


def _sample_income_from_distribution(simulation_config: Optional[Dict], rng: np.random.Generator) -> float:
    """
    Generate a single income value using Page 1 distribution parameters.
    
    This is a FALLBACK - normally income is already generated by disclose_documents.
    
    Supports three distribution types from Page 1:
    - lognormal: X = min + Y where Y ~ Lognormal(mu, sigma)
    - generalised_gamma: X = min + Y where Y ~ GenGamma(k, c, lambda)
    - dagum: X = min + Y where Y ~ Dagum(a, p, b)
    
    Args:
        simulation_config: Contains Page 1 parameters
        rng: Random number generator for reproducibility
        
    Returns:
        Generated income value (float)
    """
    from scipy import stats
    
    dist_type = _get_simulation_param(simulation_config, 'income_distribution', 'lognormal')
    
    if dist_type == 'lognormal':
        # Parameters from Page 1 UI
        mu = _get_simulation_param(simulation_config, 'lognormal_mu', 10.0)
        sigma = _get_simulation_param(simulation_config, 'lognormal_sigma', 0.5)
        min_val = _get_simulation_param(simulation_config, 'lognormal_min', 0.0)
        max_val = _get_simulation_param(simulation_config, 'lognormal_max', None)
        
        # Sample: X = min + Y where Y ~ Lognormal(mu, sigma)
        Y = stats.lognorm.rvs(s=sigma, scale=np.exp(mu), size=1, random_state=rng)[0]
        income = min_val + Y
        
        # Apply maximum if specified (rejection sampling handled in single draw)
        if max_val is not None:
            income = min(income, max_val)
            
        return float(income)
    
    elif dist_type == 'generalised_gamma':
        # Parameters from Page 1 UI
        k = _get_simulation_param(simulation_config, 'gg_k', 1.5)
        c = _get_simulation_param(simulation_config, 'gg_c', 2.0)
        lambda_param = _get_simulation_param(simulation_config, 'gg_lambda', 20000.0)
        min_val = _get_simulation_param(simulation_config, 'gg_min', 0.0)
        max_val = _get_simulation_param(simulation_config, 'gg_max', None)
        
        # Sample from Generalised Gamma: X = min + Y
        # scipy uses (a=c, c=k, scale=lambda) parameterization
        Y = stats.gengamma.rvs(a=c, c=k, scale=lambda_param, size=1, random_state=rng)[0]
        income = min_val + Y
        
        if max_val is not None:
            income = min(income, max_val)
            
        return float(income)
    
    elif dist_type == 'dagum':
        # Parameters from Page 1 UI
        a = _get_simulation_param(simulation_config, 'dagum_a', 2.0)
        p = _get_simulation_param(simulation_config, 'dagum_p', 1.5)
        b = _get_simulation_param(simulation_config, 'dagum_b', 25000.0)
        min_val = _get_simulation_param(simulation_config, 'dagum_min', 0.0)
        max_val = _get_simulation_param(simulation_config, 'dagum_max', None)
        
        # Sample using inverse CDF: Y = b * ((U^(-1/p) - 1)^(-1/a))
        U = rng.random()
        Y = b * np.power(np.power(U, -1/p) - 1, -1/a)
        income = min_val + Y
        
        if max_val is not None:
            income = min(income, max_val)
            
        return float(income)
    
    else:
        # Fallback: uniform distribution (legacy)
        min_val = _get_simulation_param(simulation_config, 'income_min', 0.0)
        max_val = _get_simulation_param(simulation_config, 'income_max', 100000.0)
        return float(rng.uniform(min_val, max_val))


def _assign_income_category(income: float, simulation_config: Optional[Dict]) -> int:
    """
    Assign agent to a fixed income category (1 to NFIC) based on their income.
    
    Logic:
    - If income <= discount_threshold: Category 1 (discount customers, lowest income)
    - If income > threshold: Categories 2 to NFIC (fixed-price customers)
      - Map uniformly across remaining categories based on income percentile
    
    This matches the CONSUMPTION_LIMITS_GUIDE.md specification:
    - Category 1 = Lowest income (discount customers)
    - Category 2-NFIC = Higher income levels (fixed-price customers)
    
    Args:
        income: Agent's annual income
        simulation_config: Contains discount_income_threshold and num_fixed_categories
        
    Returns:
        Income category number (1 to NFIC)
    """
    # Get Page 1 parameters
    threshold = _get_simulation_param(simulation_config, 'discount_income_threshold', 12500.0)
    nfic = _get_simulation_param(simulation_config, 'num_fixed_categories', 10)
    nfic = max(1, int(nfic))  # Ensure at least 1 category
    
    # Category 1: Discount customers (income <= threshold)
    if income <= threshold:
        return 1
    
    # If only 1 category exists, everyone goes there
    if nfic == 1:
        return 1
    
    # Categories 2-NFIC: Fixed-price customers
    # Simple approach: distribute uniformly based on how far above threshold
    # More sophisticated approach would use income distribution CDF, but for defaults
    # we use a simple linear mapping
    
    # Get distribution bounds to normalize income
    dist_type = _get_simulation_param(simulation_config, 'income_distribution', 'lognormal')
    
    if dist_type == 'lognormal':
        max_income = _get_simulation_param(simulation_config, 'lognormal_max', None)
        # If no max specified, use a high percentile estimate
        if max_income is None:
            # For lognormal, use mean + 3*std as rough upper bound
            mu = _get_simulation_param(simulation_config, 'lognormal_mu', 10.0)
            sigma = _get_simulation_param(simulation_config, 'lognormal_sigma', 0.5)
            min_val = _get_simulation_param(simulation_config, 'lognormal_min', 0.0)
            mean = min_val + np.exp(mu + 0.5 * sigma**2)
            std = np.sqrt((np.exp(sigma**2) - 1) * np.exp(2*mu + sigma**2))
            max_income = mean + 3 * std
    elif dist_type == 'generalised_gamma':
        max_income = _get_simulation_param(simulation_config, 'gg_max', None)
        if max_income is None:
            max_income = _get_simulation_param(simulation_config, 'gg_lambda', 20000.0) * 3
    elif dist_type == 'dagum':
        max_income = _get_simulation_param(simulation_config, 'dagum_max', None)
        if max_income is None:
            max_income = _get_simulation_param(simulation_config, 'dagum_b', 25000.0) * 3
    else:
        max_income = _get_simulation_param(simulation_config, 'income_max', 100000.0)
    
    # Normalize income position within [threshold, max_income] range
    if max_income <= threshold:
        max_income = threshold * 2  # Safety fallback
    
    # Calculate position as fraction of range above threshold
    position = (income - threshold) / (max_income - threshold)
    position = np.clip(position, 0.0, 1.0)  # Ensure [0, 1]
    
    # Map to categories 2 through NFIC
    num_categories_above_threshold = nfic - 1  # Categories 2, 3, ..., NFIC
    category_index = int(np.floor(position * num_categories_above_threshold))
    category = 2 + category_index
    
    # Ensure we don't exceed NFIC
    category = min(category, nfic)
    
    return int(category)


def consumption_quantity(agent_state: dict, params: dict, rng: np.random.Generator, 
                        simulation_config: dict = None, **kwargs) -> dict:
    """
    Decision 6: Determine consumption quantity and generate purchase requests.
    
    Default behavior (this implementation):
    1. Get/generate agent income
    2. Assign to income category (1 to NFIC)
    3. Look up consumption limit for that category
    4. Generate random total quantity in [0, limit]
    5. Create purchase requests (1 item each) spread randomly across term
    
    Args:
        agent_state: Agent's state dict (includes 'income' if set by disclose_documents)
        params: Decision-specific parameters from decisions.yaml
        rng: Random number generator for reproducibility
        simulation_config: Page 1 parameters in ['simulation'] sub-dict
        
    Returns:
        Dictionary with:
        - consumption_quantity: Total items to purchase (int)
        - purchase_requests: List of dicts with request_id, quantity=1, timestamp_hours
        - income_category: Assigned category (int, 1 to NFIC)
        - income: Agent income (stored for consistency)
    """
    
    # STEP 1: Get or generate agent income
    # Income should already exist from disclose_documents (Decision 2)
    income = agent_state.get('income')
    
    if income is None:
        # Fallback: generate using Page 1 distribution parameters
        # This shouldn't normally happen in full simulation runs
        income = _sample_income_from_distribution(simulation_config, rng)
        agent_state['income'] = income
    
    # STEP 2: Assign agent to income category (1 to NFIC)
    income_category = _assign_income_category(income, simulation_config)
    
    # STEP 3: Get consumption limit for this category
    # Check if consumption limits are enabled and configured
    consumption_limits = {}
    if isinstance(simulation_config, dict):
        consumption_limits = simulation_config.get('consumption_limits', {}) or {}
    
    # Get fallback maximum for when limits are disabled
    fallback_max = _get_simulation_param(simulation_config, 'max_purchases_per_term', 50)
    fallback_max = max(0, int(fallback_max))
    
    # Look up limit for this category
    limit_key = f"cat_{income_category}"
    if isinstance(consumption_limits, dict) and limit_key in consumption_limits:
        try:
            consumption_limit = int(consumption_limits[limit_key])
        except (ValueError, TypeError):
            consumption_limit = fallback_max
    else:
        # No limit configured for this category - use fallback
        consumption_limit = fallback_max
    
    consumption_limit = max(0, consumption_limit)  # Ensure non-negative
    
    # STEP 4: Generate total quantity for the term
    # Random integer in [0, consumption_limit] inclusive
    if consumption_limit > 0:
        total_quantity = int(rng.integers(0, consumption_limit + 1))
    else:
        total_quantity = 0
    
    # STEP 5: Generate purchase requests with timestamps
    # Professor's specification: each request = 1 item for defaults
    # Timestamps spread randomly across term duration
    
    purchase_requests = []
    
    if total_quantity > 0:
        # Calculate term duration from Page 1 parameters
        periods = _get_simulation_param(simulation_config, 'periods', 1)
        duration_hours = _get_simulation_param(simulation_config, 'duration_hours', 1.0)
        term_duration = float(periods * duration_hours)
        
        # Generate random timestamps uniformly distributed in [0, term_duration]
        # Sort them so they're in chronological order
        timestamps = sorted(rng.uniform(0, term_duration, size=total_quantity))
        
        # Create purchase request objects
        for i, timestamp in enumerate(timestamps):
            purchase_requests.append({
                "request_id": i + 1,
                "quantity": 1,  # 1 item per request for defaults
                "timestamp_hours": float(timestamp)
            })
    
    # Return results
    return {
        "consumption_quantity": int(total_quantity),
        "purchase_requests": purchase_requests,
        "income_category": int(income_category),
        "income": float(income)  # Store/update income for consistency
    }


