# Parameter Applicability Configuration
# This file defines which simulation parameters are applicable for each decision
# Parameters not listed for a decision will be marked as "Not Applicable" in the UI

decisions:
  donation_default:
    applicable_parameters:
      # Income parameters are critical for donation decisions
      - income_distribution
      - income_min
      - income_max
      - income_avg
    not_applicable_reason: "Donation decisions depend only on agent traits and income distribution"
    
  disclose_income:
    applicable_parameters:
      # Privacy decisions may depend on income levels
      - income_distribution
      - income_min
      - income_max
      - income_avg
    not_applicable_reason: "Income disclosure depends on income distribution only"
    
  disclose_documents:
    applicable_parameters:
      # Document disclosure is trait-based, no market parameters needed
      []
    not_applicable_reason: "Document disclosure is purely trait-based"
    
  rejected_transaction_defaults:
    applicable_parameters:
      # Transaction defaults may depend on market conditions
      - market_price
      - vendor_price_min
      - vendor_price_max
      - platform_markup
    not_applicable_reason: "Transaction defaults depend on market pricing only"
    
  vendor_choice_weights:
    applicable_parameters:
      # Vendor choice depends on market structure
      - num_vendors
      - market_price
      - vendor_price_min
      - vendor_price_max
    not_applicable_reason: "Vendor choice depends on market structure and pricing"
    
  consumption_quantity:
    applicable_parameters:
      # Consumption depends on income and consumption limits
      - income_distribution
      - income_min
      - income_max
      - income_avg
      - num_fixed_categories
      - consumption_limits
    not_applicable_reason: "Consumption quantity depends on income and preset limits"
    
  consumption_frequency:
    applicable_parameters:
      # Frequency may depend on time parameters
      - periods
      - duration_hours
      - income_distribution
      - income_min
      - income_max
    not_applicable_reason: "Consumption frequency depends on time and income parameters"
    
  vendor_selection:
    applicable_parameters:
      # Vendor selection depends on market structure
      - num_vendors
      - market_price
      - vendor_price_min
      - vendor_price_max
      - products_per_vendor
      - carryover
    not_applicable_reason: "Vendor selection depends on market structure and product availability"
    
  purchase_vs_bid:
    applicable_parameters:
      # Purchase vs bid decision depends on pricing structure
      - bidding_percentage
      - platform_markup
      - price_range
      - price_grid
      - market_price
    not_applicable_reason: "Purchase vs bid decision depends on auction and pricing parameters"
    
  bid_value:
    applicable_parameters:
      # Bid value depends on pricing and income
      - income_distribution
      - income_min
      - income_max
      - income_avg
      - platform_markup
      - price_range
      - price_grid
      - market_price
    not_applicable_reason: "Bid value depends on pricing structure and agent income"
    
  rejected_transaction_option:
    applicable_parameters:
      # Similar to transaction defaults
      - market_price
      - vendor_price_min
      - vendor_price_max
      - platform_markup
    not_applicable_reason: "Rejected transaction options depend on market pricing"
    
  rejected_bid_value:
    applicable_parameters:
      # Similar to bid value but for rejected scenarios
      - income_distribution
      - income_min
      - income_max
      - platform_markup
      - price_range
      - market_price
    not_applicable_reason: "Rejected bid value depends on pricing and income constraints"
    
  final_donation_rate:
    applicable_parameters:
      # Final donation may be influenced by income
      - income_distribution
      - income_min
      - income_max
      - income_avg
    not_applicable_reason: "Final donation rate depends on income distribution only"

# Global parameter categories for organization
parameter_categories:
  time_parameters:
    - periods
    - duration_hours
    
  market_parameters:
    - num_vendors
    - market_price
    - vendor_price_min
    - vendor_price_max
    
  product_parameters:
    - products_per_vendor
    - carryover
    
  pricing_parameters:
    - bidding_percentage
    - platform_markup
    - price_range
    - price_grid
    
  income_parameters:
    - income_min
    - income_max
    - income_avg
    - income_distribution
    - num_discount_categories
    - num_fixed_categories
    
  consumption_parameters:
    - consumption_limits
    
  vendor_parameters:
    - vendor_price_source
    - vendor_prices_file
